(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(which-key)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(load-file "~/code/emacs-rust-config/standalone.el")
;; 1. Define your custom Org directory
;;(setq my-org-path "/Users/c76678/code/emacs/org-mode/lisp/")

;; 2. Push it to the absolute front of the load-path
;;(if (file-directory-p my-org-path)
;;    (add-to-list 'load-path my-org-path)
;;  (message "Warning: Custom Org path not found!"))

;; 3. Prevent Emacs from loading the built-in Org features early
;;(with-eval-after-load 'org
;;  (message "Org loaded successfully from: %s" (feature-file 'org)))

;;(setq load-path (cons "~/code/emacs/org-mode/lisp" load-path))
;;(setq load-path (cons "~/code/emacs/org-mode/contrib/lisp" load-path))


(setq org-todo-keywords
      '((sequence "TODO" "INPROCESS" "WAITING" "DONE")))

;; Disable the splash screen (to enable it agin, replace the t with 0)
(setq inhibit-splash-screen t)

;; Enable transient mark mode
(transient-mark-mode 1)

;;;;Org mode configuration
;; Enable Org mode
(require 'org)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
(setq org-log-done t)

(setq package-install-upgrade-built-in t)
(setq org-agenda-files '("~/Documents/notes"))

;; Make Org mode work with files ending in .org
;; (add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
;; The above is the default in recent emacsen

(add-to-list 'load-path "~/code/emacs/org-noter-1.6.1/")
(require 'org-noter)
    
(setq org-roam-directory (file-truename "~/Documents/notes"))

(use-package org-download
  :after org
  :bind (:map org-mode-map
              (("s-Y" . org-download-screenshot)
               ("s-y" . org-download-yank)))
  :config
  (setq-default org-download-image-dir "~/Documents/data") ; Saves to an images folder
  (setq org-download-heading-lvl nil)) ; Keeps directory structure flat


;; Insert the current time in the current buffer
(defun
 timestamp()
        (interactive)
        ; If you want to insert date and time, you can use:
        (insert(format-time-string "%Y-%m-%d %H:%M:%S ")))
;; Bind Ctrl-T ("transpose") to the timestamp function - need a better key binding
(global-set-key (kbd "C-T") 'timestamp)

(defun
 agendastamp()
        (interactive)
        ; If you want to insert date and time, you can use:
        (insert(format-time-string "** <%Y-%m-%d> ")))
;; Bind Ctrl-T ("transpose") to the timestamp function - need a better key binding
(global-set-key (kbd "C-t") 'agendastamp)
(require 'ox-md)

;; (use-package which-key
;;   :ensure
;;   :init
;;   (which-key-mode))
